-- MySQL Script generated by MySQL Workbench
-- Wed Dec 29 22:19:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lista-qi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lista-qi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lista-qi` DEFAULT CHARACTER SET utf8 ;
USE `lista-qi` ;

-- -----------------------------------------------------
-- Table `lista-qi`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista-qi`.`cliente` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(70) NULL,
  `logradouro` VARCHAR(70) NULL,
  `bairro` VARCHAR(70) NULL,
  `estado` VARCHAR(70) NULL,
  `nome` VARCHAR(70) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `senha` VARCHAR(70) NOT NULL,
  `imagem` LONGBLOB NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista-qi`.`lista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista-qi`.`lista` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `qtdeTotalProdutos` INT NOT NULL,
  `precoTotal` DOUBLE NOT NULL,
  `codigo` INT NOT NULL,
  `nome` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `codigo_idx` (`codigo` ASC) ,
  CONSTRAINT `codigo`
    FOREIGN KEY (`codigo`)
    REFERENCES `lista-qi`.`cliente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista-qi`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista-qi`.`produto` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista-qi`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista-qi`.`empresa` (
  `cnpj` INT NOT NULL,
  `nome` VARCHAR(70) NOT NULL,
  `senha` VARCHAR(70) NOT NULL,
  `cidade` VARCHAR(70) NULL,
  `logradouro` VARCHAR(70) NULL,
  `bairro` VARCHAR(70) NULL,
  `estado` VARCHAR(70) NULL,
  `email` VARCHAR(70) NOT NULL,
  `imagem` LONGBLOB NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista-qi`.`listaproduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista-qi`.`listaproduto` (
  `numero` INT NOT NULL,
  `codigo` INT NOT NULL,
  `qtde` INT NOT NULL,
  `cnpj` INT NOT NULL,
  PRIMARY KEY (`numero`, `codigo`),
  INDEX `codigo_idx` (`codigo` ASC) ,
  INDEX `cnpj_lp_idx` (`cnpj` ASC) ,
  CONSTRAINT `numero_lp`
    FOREIGN KEY (`numero`)
    REFERENCES `lista-qi`.`lista` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigo_lp`
    FOREIGN KEY (`codigo`)
    REFERENCES `lista-qi`.`produto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cnpj_lp`
    FOREIGN KEY (`cnpj`)
    REFERENCES `lista-qi`.`empresa` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lista-qi`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista-qi`.`venda` (
  `cnpj` INT NOT NULL,
  `codigo` INT NOT NULL,
  `qtde` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`cnpj`, `codigo`),
  INDEX `codigo_idx` (`codigo` ASC) ,
  CONSTRAINT `cnpj_v`
    FOREIGN KEY (`cnpj`)
    REFERENCES `lista-qi`.`empresa` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigo_v`
    FOREIGN KEY (`codigo`)
    REFERENCES `lista-qi`.`produto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
